-- Widen job text columns (H2 / MySQL-style). Safe to run on every startup.
-- H2 file DB path in Docker: /app/data/hirenest_db

ALTER TABLE IF EXISTS job ALTER COLUMN IF EXISTS description SET DATA TYPE CLOB;
ALTER TABLE IF EXISTS job ALTER COLUMN IF EXISTS required_skills SET DATA TYPE VARCHAR(2000);
ALTER TABLE IF EXISTS job ALTER COLUMN IF EXISTS title SET DATA TYPE VARCHAR(512);
ALTER TABLE IF EXISTS job ALTER COLUMN IF EXISTS company_name SET DATA TYPE VARCHAR(512);
ALTER TABLE IF EXISTS job ALTER COLUMN IF EXISTS location SET DATA TYPE VARCHAR(512);
