spring.application.name=hirenest-backend

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/hirenest_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=kAUSTAv1409

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=hirenest-super-secret-key-hirenest-super-secret-key
app.jwt.expiration-ms=86400000
google.client.id=212570088909-jgdkgiavkb23nvhlngiep5pq6p03liup.apps.googleusercontent.com
app.google.client-id=212570088909-jgdkgiavkb23nvhlngiep5pq6p03liup.apps.googleusercontent.com

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

